name: Sync Airflow and S3

on:
  push:
    branches:
      - develop

env:
    MASTER_DAGS_DIR: /home/ec2-user/airflow_master/dags
    #WORKER_DAGS_DIR: /home/ec2-user/airflow_worker/dags
    DOCKER_COMPOSE_DIR: /home/ec2-user/airflow_master/docker-compose.yaml
    #WORKER_IPS: ${{ secrets.WORKER1_PRIVATE_IP }} ${{ secrets.WORKER2_PRIVATE_IP }} ${{ secrets.WORKER3_PRIVATE_IP }}

jobs:
    sync-dags:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            # 1. Sync Github and S3
            - name: Show AWS version
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ap-northeast-2

            - name: Sync S3 bucket and Github
              run: |
                aws s3 sync ./data s3://team6-s3/data --delete
            
            # 2. Sync Github and Airflow DAGs
            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.5.3
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
            - name: Add known hosts
              run: |
                echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

            - name: Sync DAGs to Master Node
              run: |
                ssh ec2-user@${{ secrets.MASTER_IP }} 'cp /etc/skel/.bashrc ~/.bashrc' && 
                scp -r ./airflow/dags/* ec2-user@${{ secrets.MASTER_IP }}:$MASTER_DAGS_DIR
                scp ./airflow/docker-compose.yaml ec2-user@${{ secrets.MASTER_IP }}:$DOCKER_COMPOSE_DIR

            #- name: Sync DAGs to Worker Nodes
            #  run: |  
            #    for WORKER_IP in $WORKER_IPS; do
            #      ssh -A ec2-user@${{ secrets.MASTER_IP }} "scp -r $MASTER_DAGS_DIR/* ec2-user@$WORKER_IP:$WORKER_DAGS_DIR" 
            #    done