name: Build and Deploy Airflow to EC2

on:
    push:
        branches:
        - develop
        - feat/github-action-hyerim

env:
    PROJECT_DIR: /home/ec2-user/airflow_project
    WORKER_IPS: ${{ secrets.WORKER1_PRIVATE_IP }} ${{ secrets.WORKER2_PRIVATE_IP }} ${{ secrets.WORKER3_PRIVATE_IP }}

jobs:
    build:
        runs-on: ubuntu-latest
        if: >  
          contains(github.event.head_commit.message, '[build-trigger]')

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
    
            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.5.3
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
            - name: Add known hosts
              run: |
                echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
    
            - name: Sync Master Node
              run: |
                ssh ec2-user@${{ secrets.MASTER_IP }} "mkdir -p $PROJECT_DIR"
                rsync -avz ./ ec2-user@${{ secrets.MASTER_IP }}:$PROJECT_DIR
    
            - name: Load .env to Master Node and Apply Environment Variables
              run: |
                ssh ec2-user@${{ secrets.MASTER_IP }} "
                    cd $PROJECT_DIR/airflow &&
                    export \$(cat .env | xargs) &&
                    echo 'export \$(cat $PROJECT_DIR/airflow/.env | xargs)' >> ~/.bashrc &&
                    source ~/.bashrc
                    "
                
            - name: Set Permissions on Logs Directory (Master Node)
              run: |
                ssh -A ec2-user@${{ secrets.MASTER_IP }} "
                mkdir -p $PROJECT_DIR/airflow/logs &&
                sudo chmod -R 777 $PROJECT_DIR/airflow/logs
                "

            - name: Copy Airflow Project to Worker Nodes
              run: |
                for WORKER_IP in $WORKER_IPS; do
                  ssh -A ec2-user@${{ secrets.MASTER_IP }} "ssh ec2-user@$WORKER_IP 'mkdir -p $PROJECT_DIR'"
                  ssh -A ec2-user@${{ secrets.MASTER_IP }} "rsync -avz $PROJECT_DIR/ ec2-user@$WORKER_IP:$PROJECT_DIR/"
                done
    
            - name: Build to Worker Nodes (Docker Build and Cleanup)
              run: |
                for WORKER_IP in $WORKER_IPS; do
                  ssh -A ec2-user@${{ secrets.MASTER_IP }} "
                    ssh ec2-user@$WORKER_IP '
                      docker stop airflow-worker || true &&
                      docker rm airflow-worker || true &&
                      docker image prune -af &&
                      docker build --pull -t airflow-worker -f $PROJECT_DIR/airflow/Dockerfile $PROJECT_DIR/airflow
                    '
                  "
                done
            
            - name: Clean up space
              run: |
                sudo apt-get clean
                sudo apt-get autoremove -y
                sudo rm -rf /usr/share/dotnet
                sudo rm -rf /usr/local/lib/android
                sudo rm -rf /opt/ghc
                sudo rm -rf /var/lib/apt/lists/*
                sudo rm -rf /var/cache/apt/archives/*
                df -h
                    
                  
            - name: Initialize Airflow (DB Init)
              run: |
                ssh ec2-user@${{ secrets.MASTER_IP }} "
                    cd $PROJECT_DIR/airflow &&
                    docker-compose down &&
                    docker-compose up -d &&
                    docker-compose exec -T airflow-webserver env PGPASSWORD='postgres' psql \
                    -h team6-postgres-for-airflow.ch4xfyi6stod.ap-northeast-2.rds.amazonaws.com \
                    -U postgres \
                    -d airflow \
                    -c 'DROP SCHEMA public CASCADE; CREATE SCHEMA public;' &&
                    docker-compose exec -T airflow-webserver airflow db init &&
                    docker-compose restart
                "



    deploy:
        runs-on: ubuntu-latest
        needs: [build]
        if: ${{ always() }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
    
            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.5.3
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
            - name: Add known hosts
              run: |
                echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

            - name: Sync Master Node
              run: |
                ssh ec2-user@${{ secrets.MASTER_IP }} "mkdir -p $PROJECT_DIR"
                rsync -avz ./ ec2-user@${{ secrets.MASTER_IP }}:$PROJECT_DIR

            - name: Copy Airflow Project to Worker Nodes
              run: |
                for WORKER_IP in $WORKER_IPS; do
                  ssh -A ec2-user@${{ secrets.MASTER_IP }} "ssh ec2-user@$WORKER_IP 'mkdir -p $PROJECT_DIR'"
                  ssh -A ec2-user@${{ secrets.MASTER_IP }} "rsync -avz $PROJECT_DIR/ ec2-user@$WORKER_IP:$PROJECT_DIR/"
                done

            - name: Deploy to Worker Nodes (Docker Run)
              run: |
                for WORKER_IP in $WORKER_IPS; do
                  ssh -A ec2-user@${{ secrets.MASTER_IP }} "
                    ssh ec2-user@$WORKER_IP '
                      docker stop airflow-worker || true &&
                      docker rm airflow-worker || true &&
                      docker run -d --name airflow-worker airflow-worker
                    '
                  "
                done
              
            - name: Start Airflow on Master
              run: |
                ssh ec2-user@${{ secrets.MASTER_IP }} "
                    cd $PROJECT_DIR/airflow &&
                    docker-compose down &&
                    docker-compose up -d &&
                    docker-compose exec -T airflow-webserver airflow db upgrade &&
                    docker-compose restart
                "